<a href="https://colab.research.google.com/github/9characters/2D-Poster_injection/blob/master/Colab_2_TensorFlow_2_0_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X




### Installing TensorFlow 1.X



In [ ]:
#!pip install tensorflow-gpu

In [2]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'1.15.2'

### Constants

#### Defining a constant

In [32]:
# Defining a TensorFlow constant
tensor = tf.constant([[26, 81], [45, 75]])

In [8]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [9]:
# If a session is not initialized, we cannot access the values of the constant
tensor.eval()

ValueError: ignored

#### Getting the values of a constant

In [29]:
session = tf.Session()

In [30]:
session.run(tf.global_variables_initializer())

In [26]:
tensor_value = session.run(tensor)

In [27]:
tensor_value

array([[26, 81],
       [45, 75]], dtype=int32)

### Variables

#### Defining a variable

In [16]:
variable = tf.Variable([[26, 81], [45, 75]])

In [17]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [18]:
variable.eval()

ValueError: ignored

#### Getting the values of a variable

In [20]:
# Initializing a session
session = tf.Session()

In [22]:
# Initializing ALL the variables from the session
session.run(tf.global_variables_initializer())

In [23]:
# Running the eval method on the environment with the initialized session to retrieve values from it
variable.eval(session)

array([[26, 81],
       [45, 75]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [ ]:
#!pip install tensorflow-gpu==2.0.0-alpha0

In [2]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.6.0'

### Constants

#### Defining a constant

In [4]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
# Getting the shape of a tensor
tensor_20.shape

TensorShape([2, 2])

#### Getting the values of a constant

In [7]:
# Getting the values straight from a TensorFlow constant with numpy, and without the need of a session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [12]:
# We are able to convert a numpy array back to a TensorFlow tensor as well
numpy_tensor = np.array([[26, 81], [45, 75]])

In [13]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [14]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[26, 81],
       [45, 75]])>

### Variables

#### Defining a variable

In [17]:
tf2_variable = tf.Variable([[26, 81], [45, 75], [44, 67]])
tf2_variable

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[26, 81],
       [45, 75],
       [44, 67]], dtype=int32)>

#### Getting the values of a variable

In [18]:
tf2_variable.numpy()

array([[26, 81],
       [45, 75],
       [44, 67]], dtype=int32)

#### Changing a specific value in the variable

In [19]:
tf2_variable[2,1].assign(68)

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=int32, numpy=
array([[26, 81],
       [45, 75],
       [44, 68]], dtype=int32)>

In [21]:
tf2_variable

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[26, 81],
       [45, 75],
       [44, 68]], dtype=int32)>

### Operations with tensors

In [12]:
tensor = tf.constant([[26,81], [45,75]])

#### Addition between a scalar and a tensor

In [13]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 83],
       [47, 77]], dtype=int32)>

#### Multiplication between a scalar and a tensor

In [14]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[130, 405],
       [225, 375]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [17]:
np.square(tensor)

numpy.ndarray

In [16]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 81],
       [45, 75]], dtype=int32)>

In [11]:
print(type(tensor))

<class 'numpy.ndarray'>


In [ ]:
# Getting the squares of all numbers in a TensorFlow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [18]:
# Getting the square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[5.09901951, 9.        ],
       [6.70820393, 8.66025404]])

#### Dot product between two tensors

In [23]:
tensor = tf.constant([[2,3], [4,5]])

In [24]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>

In [25]:
np.dot(tensor, tensor)

array([[16, 21],
       [28, 37]], dtype=int32)

### Strings in TensorFlow 2.0

In [26]:
tf_string = tf.constant("Hello There")

In [27]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello There'>

In [29]:
print(tf.strings.length(tf_string))

tf.Tensor(11, shape=(), dtype=int32)


In [ ]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=62, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: id=49, shape=(), dtype=int32, numpy=10>

In [33]:
string = tf.constant("abcdef")

In [35]:
tf.strings.unicode_decode(string, "ASCII")

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 97,  98,  99, 100, 101, 102], dtype=int32)>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=58, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Storing arrays of strings

In [36]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
